package filter

import (
	"regexp"
	"strings"
)

// Node is a parsed filter expression. Walk via type switch in the evaluator.
type Node interface {
	node()
	String() string
}

type AndNode struct{ L, R Node }
type OrNode struct{ L, R Node }
type NotNode struct{ X Node }

// EqNode matches Path equality with V (string equality).
type EqNode struct {
	Path []string
	V    string
}

// SubstrNode matches a substring within Path's string value.
// Exact = true means the value must equal V (no substring search).
// Glob, when non-nil, is used in place of Needle: the value must match
// the anchored glob pattern (parts alternate literal/wild).
type SubstrNode struct {
	Path   []string
	Needle string
	Exact  bool
	Glob   []GlobPart
}

// ExistsNode matches when materializeField(Path) returns a non-empty
// string. Generated by `field:*` tokens.
type ExistsNode struct {
	Path []string
}

// GlobPart is one segment of a glob pattern. Alternating literal/wild.
// A Wild=true part matches any sequence (including empty).
type GlobPart struct {
	Lit  string
	Wild bool
}

// RangeNode matches Path numeric value in [Lo, Hi].
type RangeNode struct {
	Path   []string
	Lo, Hi float64
}

// CmpNumNode matches Path numeric value against N with operator Op (one of
// ">", ">=", "<", "<=").
type CmpNumNode struct {
	Path []string
	Op   string
	N    float64
}

// CmpStrNode is the ordinal-string variant (e.g. level:>=info). The compiler
// resolves V to its level ordinal.
type CmpStrNode struct {
	Path []string
	Op   string
	V    string
}

// RegexNode matches Path's string value against a /pattern/flags literal.
// Re is pre-compiled at parse time so bad regex errors surface up front.
type RegexNode struct {
	Path    []string
	Pattern string
	Flags   string
	Re      *regexp.Regexp
}

func (*AndNode) node()     {}
func (*OrNode) node()      {}
func (*NotNode) node()     {}
func (*EqNode) node()      {}
func (*SubstrNode) node()  {}
func (*ExistsNode) node()  {}
func (*RangeNode) node()   {}
func (*CmpNumNode) node()  {}
func (*CmpStrNode) node()  {}
func (*RegexNode) node()   {}

func (n *AndNode) String() string    { return "(" + n.L.String() + " AND " + n.R.String() + ")" }
func (n *OrNode) String() string     { return "(" + n.L.String() + " OR " + n.R.String() + ")" }
func (n *NotNode) String() string    { return "NOT " + n.X.String() }
func (n *EqNode) String() string     { return joinPath(n.Path) + ":" + n.V }
func (n *SubstrNode) String() string {
	if n.Glob != nil {
		var b strings.Builder
		for _, p := range n.Glob {
			if p.Wild {
				b.WriteByte('*')
			} else {
				b.WriteString(p.Lit)
			}
		}
		return joinPath(n.Path) + `:"` + b.String() + `"`
	}
	return joinPath(n.Path) + ":~" + n.Needle
}
func (n *ExistsNode) String() string { return joinPath(n.Path) + ":*" }
func (n *RangeNode) String() string  { return joinPath(n.Path) + ":[range]" }
func (n *CmpNumNode) String() string { return joinPath(n.Path) + ":" + n.Op }
func (n *CmpStrNode) String() string { return joinPath(n.Path) + ":" + n.Op + n.V }
func (n *RegexNode) String() string  { return joinPath(n.Path) + ":/" + n.Pattern + "/" + n.Flags }

func joinPath(p []string) string {
	if len(p) == 0 {
		return ""
	}
	if len(p) == 1 {
		return p[0]
	}
	out := "@" + p[0]
	for i := 1; i < len(p); i++ {
		out += "." + p[i]
	}
	return out
}
