package app

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/iOliverNguyen/loggi/internal/config"
	"github.com/spf13/cobra"
)

const initTemplate = `# loggi config
# See README for the full schema.

[server]
idle_timeout = "5m"
ring_buffer  = 524288

[ui]
theme            = "auto"
default_profile  = "dev"
timestamp_format = "15:04:05.000"

[[profiles]]
name    = "dev"
filter  = 'level:>=info'
columns = ["ts", "level", "service", "msg"]

[[profiles]]
name    = "errors"
filter  = 'level:>=warn'
columns = ["ts", "level", "service", "msg", "trace_id"]
`

// NewInitCmd scaffolds a repo config file.
func NewInitCmd() *cobra.Command {
	var force bool
	cmd := &cobra.Command{
		Use:   "init",
		Short: "Scaffold a repo-level loggi config",
		RunE: func(_ *cobra.Command, _ []string) error {
			cwd, err := os.Getwd()
			if err != nil {
				return err
			}
			repo := config.FindRepoRoot(cwd)
			if repo == "" {
				return fmt.Errorf("no repo root (.git or go.mod) found above %s", cwd)
			}
			committed, _ := config.RepoConfigPaths(repo)
			if _, err := os.Stat(committed); err == nil && !force {
				return fmt.Errorf("%s already exists (use --force to overwrite)", committed)
			}
			if err := os.MkdirAll(filepath.Dir(committed), 0o755); err != nil {
				return err
			}
			if err := os.WriteFile(committed, []byte(initTemplate), 0o644); err != nil {
				return err
			}
			fmt.Println("wrote", committed)
			// Append *.local.toml to a sibling .gitignore if present.
			gi := filepath.Join(repo, ".gitignore")
			if data, err := os.ReadFile(gi); err == nil {
				rel, relErr := filepath.Rel(repo, filepath.Dir(committed))
				if relErr != nil {
					return fmt.Errorf("relpath for %s: %w", filepath.Dir(committed), relErr)
				}
				entry := filepath.Join(rel, "loggi.local.toml")
				if !strings.Contains(string(data), entry) {
					f, err := os.OpenFile(gi, os.O_APPEND|os.O_WRONLY, 0o644)
					if err != nil {
						return fmt.Errorf("open %s: %w", gi, err)
					}
					if _, err := fmt.Fprintf(f, "\n# loggi local override (generated by `loggi init`)\n%s\n", entry); err != nil {
						_ = f.Close()
						return fmt.Errorf("append to %s: %w", gi, err)
					}
					if err := f.Close(); err != nil {
						return fmt.Errorf("close %s: %w", gi, err)
					}
					fmt.Println("appended to", gi)
				}
			}
			return nil
		},
	}
	cmd.Flags().BoolVar(&force, "force", false, "overwrite if file exists")
	return cmd
}
